[[examples]]
name = "Paragraph"
org = "Hello World."
desc = "Paragraph represents a consecutive lines of non-special lines."

[[examples]]
name = "Section"
org = """
* Headline 1
And this is the content.
** Headline 1.1
*** Headline 1.1.1
* Headline 2
"""
desc = "Section starts with a headline, and it can be nested."

[[examples]]
name = "Headline"
org = """
* TODO [#A] Hello World   :tag1:tag2:
DEADLINE: <2018-01-01 Mon>
:PROPERTY:
key0: value0
key1: value1
:END:
"""
desc = "Headline can have keyword, priority, tags, planning, drawers."

[[examples]]
name = "Blocks"
org = """
#+BEGIN_SRC javascript
const parser = new Parser()
const ast = parser.parse(`Hello World`)
#+END_SRC
"""

[[examples]]
name = "List and List Item"
org = """
- [x] build an awesome org-mode parser
- [ ] let people use it everywhere
- orga :: the ultimate org-mode parser
"""

[[examples]]
name = "Table, Table Row and Table Cell"
org = """
| foo | bar |
|-----|-----|
| baz | qux |
"""

[[examples]]
name = "Horizontal Rule"
org = "-----"

[[examples]]
name = "Inline Markup"
org = "_Orga_ is +probably+ the *best* /org-mode/ ~parser~ =alive=."

[[examples]]
name = "Link"
org = "Find the Source [[https://github.com/xiaoxinghu/orgajs][Here]]"

[[examples]]
name = "Export"
org = "#+HTML: <p>Hello World.</p>"

[[examples]]
name = "Export Block"
org = """
#+BEGIN_EXPORT html
<div>
    <p>Hello World.</p>
</div>
#+END_EXPORT
"""
