name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 12
    - name: bootstrap and test
      run: |
        yarn run bootstrap
        yarn test
